-- THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY THIS FILE!

-- Level objects
resource "LevelObjects" "Dawn_TrialsAir" { level = "Dawn_TrialsAir", source = "Levels/Dawn_TrialsAir/Objects.level", sourcesCount = 13, sources = { "Levels/Dawn_TrialsAir/Objects.level", "Levels/Dawn_TrialsAir/Audio.level", "Levels/Dawn_TrialsAir/Candles.level", "Levels/Dawn_TrialsAir/Ceiling.level", "Levels/Dawn_TrialsAir/FinalStretch.level", "Levels/Dawn_TrialsAir/Floors.level", "Levels/Dawn_TrialsAir/LaunchPads.level", "Levels/Dawn_TrialsAir/Map.level", "Levels/Dawn_TrialsAir/MeditationShrine.level", "Levels/Dawn_TrialsAir/Outer.level", "Levels/Dawn_TrialsAir/Revelation.level", "Levels/Dawn_TrialsAir/Scripting.level", "Levels/Dawn_TrialsAir/Winds.level" }, stripDebug = true }

-- Prefabs

-- Haptics

-- Meshes
resource "Mesh" "EyeGlowSphere_01" { source = "EyeGlowSphere_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = false, stripAnimation = false }
resource "Mesh" "FriendshipStatue_L9" { source = "FriendshipStatue_L9.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "LightShaft_02" { source = "LightShaft_02.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = false, stripAnimation = false }
resource "Mesh" "PropAP02ShrineBase" { source = "PropAP02ShrineBase.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "RockSimple_05" { source = "RockSimple_05.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "StonePath_03" { source = "StonePath_03.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "TrialPlatformCone_01" { source = "TrialPlatformCone_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "TrialPlatformCone_02" { source = "TrialPlatformCone_02.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "TrialShrineLarge_03" { source = "TrialShrineLarge_03.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "TrialShrineLarge_03b" { source = "TrialShrineLarge_03b.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "TrialShrineSmall_01" { source = "TrialShrineSmall_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }

-- Animations

-- Images
resourceref "Image" "Clear"
resourceref "Image" "FriendshipStatue"
resourceref "Image" "FriendshipStatueSh"
resourceref "Image" "Noise3Ch"
resourceref "Image" "Orange"
resourceref "Image" "StoneBase"
resourceref "Image" "StoneBaseSh"
resourceref "Image" "StoneGrunge2"
resourceref "Image" "StoneRamp"
resourceref "Image" "StoneRampGray"
resourceref "Image" "UpNormal"
resourceref "Image" "White"

-- Required resources from level object metadata

-- Bake data
resource "LevelData" "Dawn_TrialsAir" { source = "Levels/Dawn_TrialsAir/BstBaked.meshes", lodToLoad = 0 }
