-- THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY THIS FILE!

-- Level objects
resource "LevelObjects" "Event_Arr_EyesOfAChild" { level = "Event_Arr_EyesOfAChild", source = "Levels/Event_Arr_EyesOfAChild/Objects.level", sourcesCount = 4, sources = { "Levels/Event_Arr_EyesOfAChild/Objects.level", "Levels/Event_Arr_EyesOfAChild/Creatures.level", "Levels/Event_Arr_EyesOfAChild/Env_Lights.level", "Levels/Event_Arr_EyesOfAChild/EtherealAurora.level" }, stripDebug = true }

-- Prefabs
resource "LevelObjects" "BlobPrefab_SandDune_10" { level = "SandDune_10", source = "BlobPrefabs/SandDune_10/Objects.level", sourcesCount = 1, sources = { "BlobPrefabs/SandDune_10/Objects.level" }, stripDebug = true }
resource "LevelObjects" "BlobPrefab_SandDune_20" { level = "SandDune_20", source = "BlobPrefabs/SandDune_20/Objects.level", sourcesCount = 1, sources = { "BlobPrefabs/SandDune_20/Objects.level" }, stripDebug = true }
resource "LevelObjects" "BlobPrefab_SandDune_30" { level = "SandDune_30", source = "BlobPrefabs/SandDune_30/Objects.level", sourcesCount = 1, sources = { "BlobPrefabs/SandDune_30/Objects.level" }, stripDebug = true }

-- Haptics

-- Meshes
resource "Mesh" "AP16Butterfly_01" { source = "AP16Butterfly_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "AP16EyesofChildDeadPose_01" { source = "AP16EyesofChildDeadPose_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "AP16EyesofChildDeadPose_02" { source = "AP16EyesofChildDeadPose_02.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "AP16EyesofChildDeadPose_03" { source = "AP16EyesofChildDeadPose_03.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "AP16EyesofChildDeadPose_04" { source = "AP16EyesofChildDeadPose_04.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "AP16MaleCivPose_01" { source = "AP16MaleCivPose_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "AP16MaleCivPose_02" { source = "AP16MaleCivPose_02.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "AP16MaleCivPose_03" { source = "AP16MaleCivPose_03.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "AP16MaleKnightPose_01" { source = "AP16MaleKnightPose_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "AP16MaleKnightPose_02" { source = "AP16MaleKnightPose_02.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "BirdA" { source = "BirdA.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "CharBirdLowAnim" { source = "CharBirdLowAnim.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = false, stripAnimation = false }
resource "Mesh" "CharSkyRayMotherAnim" { source = "CharSkyRayMotherAnim.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "CloudCard_13" { source = "CloudCard_13.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = false, stripAnimation = false }
resource "Mesh" "CloudCard_20" { source = "CloudCard_20.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = false, stripAnimation = false }
resource "Mesh" "Cube" { source = "Cube.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "EtherealAurora" { source = "EtherealAurora.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "EyesOfAChild_Statue1" { source = "EyesOfAChild_Statue1.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "EyesOfAChild_Statue2" { source = "EyesOfAChild_Statue2.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "EyesOfAChild_Statue3" { source = "EyesOfAChild_Statue3.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "EyesOfAChild_Statue4" { source = "EyesOfAChild_Statue4.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "EyesOfAChild_Statue5" { source = "EyesOfAChild_Statue5.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "LightningBolt" { source = "LightningBolt.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = false, stripAnimation = false }
resource "Mesh" "Plane" { source = "Plane.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "SkyKidAbstractA" { source = "SkyKidAbstractA.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "SphereCheap_01" { source = "SphereCheap_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "Sphere_01" { source = "Sphere_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }

-- Animations

-- Images
resourceref "Image" "BasicGeoAtlas1"
resourceref "Image" "Black"
resourceref "Image" "CharRampAuroraNPC2"
resourceref "Image" "CharSkyRayBasicTex"
resourceref "Image" "CharSkyRayBasicTexSh"
resourceref "Image" "StoneBase"
resourceref "Image" "StoneBaseSh"
resourceref "Image" "StoneRamp"
resourceref "Image" "UpNormal"
resourceref "Image" "White"
resourceref "Image" "Yellow"

-- Required resources from level object metadata

-- Bake data
resource "LevelData" "Event_Arr_EyesOfAChild" { source = "Levels/Event_Arr_EyesOfAChild/BstBaked.meshes", lodToLoad = 0 }
