-- THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY THIS FILE!

-- Level objects
resource "LevelObjects" "Dawn_TrialsWater" { level = "Dawn_TrialsWater", source = "Levels/Dawn_TrialsWater/Objects.level", sourcesCount = 13, sources = { "Levels/Dawn_TrialsWater/Objects.level", "Levels/Dawn_TrialsWater/Audio.level", "Levels/Dawn_TrialsWater/Aurora.level", "Levels/Dawn_TrialsWater/CandleRewards.level", "Levels/Dawn_TrialsWater/FinalStretch.level", "Levels/Dawn_TrialsWater/Map.level", "Levels/Dawn_TrialsWater/MeditationShrine.level", "Levels/Dawn_TrialsWater/Outer.level", "Levels/Dawn_TrialsWater/Revelation.level", "Levels/Dawn_TrialsWater/Scripting.level", "Levels/Dawn_TrialsWater/SteppingStones.level", "Levels/Dawn_TrialsWater/SteppingStones_Targets.level", "Levels/Dawn_TrialsWater/Water.level" }, stripDebug = true }

-- Prefabs

-- Haptics

-- Meshes
resource "Mesh" "EyeGlowSphere_01" { source = "EyeGlowSphere_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = false, stripAnimation = false }
resource "Mesh" "FogCylinder" { source = "FogCylinder.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = false, stripAnimation = false }
resource "Mesh" "GodLightTemple" { source = "GodLightTemple.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = false, stripAnimation = false }
resource "Mesh" "LightShaft_02" { source = "LightShaft_02.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = false, stripAnimation = false }
resource "Mesh" "Plane" { source = "Plane.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "PropAP02ShrineBase" { source = "PropAP02ShrineBase.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "RockSimple_05" { source = "RockSimple_05.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "ScrollingFog_02" { source = "ScrollingFog_02.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = false, stripAnimation = false }
resource "Mesh" "TrialPlatformIce_01" { source = "TrialPlatformIce_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "TrialRisingIce_01" { source = "TrialRisingIce_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "TrialRisingIce_02" { source = "TrialRisingIce_02.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "TrialShrineLarge_01" { source = "TrialShrineLarge_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "TrialShrineLarge_01b" { source = "TrialShrineLarge_01b.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "TrialShrineSmall_01" { source = "TrialShrineSmall_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }

-- Animations

-- Images
resourceref "Image" "Clear"
resourceref "Image" "CloudFarTex"
resourceref "Image" "DawnIntroGate"
resourceref "Image" "DawnIntroGateSh"
resourceref "Image" "GlacierSh"
resourceref "Image" "Gray"
resourceref "Image" "GrayD2"
resourceref "Image" "GrayL1"
resourceref "Image" "Noise3Ch"
resourceref "Image" "Orange"
resourceref "Image" "OrangeL2"
resourceref "Image" "Red"
resourceref "Image" "StoneBase"
resourceref "Image" "StoneBaseMotif"
resourceref "Image" "StoneBaseSh"
resourceref "Image" "StoneGrunge"
resourceref "Image" "StoneGrunge2"
resourceref "Image" "StoneRampGray"
resourceref "Image" "TileFloorSh"
resourceref "Image" "UpNormal"
resourceref "Image" "White"
resourceref "Image" "Yellow"
resourceref "Image" "YellowD2"

-- Required resources from level object metadata

-- Bake data
resource "LevelData" "Dawn_TrialsWater" { source = "Levels/Dawn_TrialsWater/BstBaked.meshes", lodToLoad = 0 }
