-- THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY THIS FILE!

-- Level objects
resource "LevelObjects" "Prairie_WildLifePark" { level = "Prairie_WildLifePark", source = "Levels/Prairie_WildLifePark/Objects.level", sourcesCount = 33, sources = { "Levels/Prairie_WildLifePark/Objects.level", "Levels/Prairie_WildLifePark/AP19FetchQuest1.level", "Levels/Prairie_WildLifePark/AP19FetchQuest2.level", "Levels/Prairie_WildLifePark/AP19FetchQuest3.level", "Levels/Prairie_WildLifePark/AP19FetchQuest4.level", "Levels/Prairie_WildLifePark/AP19FetchQuest5.level", "Levels/Prairie_WildLifePark/AP19FetchQuests.level", "Levels/Prairie_WildLifePark/Audio.level", "Levels/Prairie_WildLifePark/Birds.level", "Levels/Prairie_WildLifePark/Diamond.level", "Levels/Prairie_WildLifePark/Dotsonologist_Test.level", "Levels/Prairie_WildLifePark/EnergySource.level", "Levels/Prairie_WildLifePark/Entrance.level", "Levels/Prairie_WildLifePark/FarmersMarket.level", "Levels/Prairie_WildLifePark/FarmersMarket_CrabWalk.level", "Levels/Prairie_WildLifePark/FarmersMarket_SassySpirit.level", "Levels/Prairie_WildLifePark/HideLayers.level", "Levels/Prairie_WildLifePark/Manatee.level", "Levels/Prairie_WildLifePark/MapShrine.level", "Levels/Prairie_WildLifePark/S19_Outro.level", "Levels/Prairie_WildLifePark/S19_SpiritQuest_Geologist.level", "Levels/Prairie_WildLifePark/S19_SpiritQuest_Zoologist.level", "Levels/Prairie_WildLifePark/S19_SpiritQuests.level", "Levels/Prairie_WildLifePark/Safenet.level", "Levels/Prairie_WildLifePark/ScriptedLevelChanges.level", "Levels/Prairie_WildLifePark/Temp.level", "Levels/Prairie_WildLifePark/TerrainCrystalCave.level", "Levels/Prairie_WildLifePark/TerrainEastSide.level", "Levels/Prairie_WildLifePark/TerrainIntro.level", "Levels/Prairie_WildLifePark/TerrainNorth.level", "Levels/Prairie_WildLifePark/TerrainWestSide.level", "Levels/Prairie_WildLifePark/WingbuffAndWax.level", "Levels/Prairie_WildLifePark/test.level" }, stripDebug = true }

-- Prefabs
resource "LevelObjects" "BlobPrefab_PrairieMountain_04" { level = "PrairieMountain_04", source = "BlobPrefabs/PrairieMountain_04/Objects.level", sourcesCount = 1, sources = { "BlobPrefabs/PrairieMountain_04/Objects.level" }, stripDebug = true }

-- Haptics

-- Meshes
resource "Mesh" "AP13PropCoral_02" { source = "AP13PropCoral_02.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = false, stripAnimation = false }
resource "Mesh" "AP13PropCoral_02b" { source = "AP13PropCoral_02b.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = false, stripAnimation = false }
resource "Mesh" "AP19WhistleStone" { source = "AP19WhistleStone.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "BirdA" { source = "BirdA.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "BoatDayAnim_01" { source = "BoatDayAnim_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "CharBirdDawnAnim" { source = "CharBirdDawnAnim.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "CharBirdJayAnim" { source = "CharBirdJayAnim.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "CharBirdJayAnim_FlapLoop" { source = "CharBirdJayAnim_FlapLoop.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "CharEnvFlowerAnim" { source = "CharEnvFlowerAnim.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = false, stripAnimation = false }
resource "Mesh" "CharSkyKid_Prop_AP19CrystalJar" { source = "CharSkyKid_Prop_AP19CrystalJar.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "CharSkyManateeBabyAnim" { source = "CharSkyManateeBabyAnim.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "CloudCard_01" { source = "CloudCard_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = false, stripAnimation = false }
resource "Mesh" "CloudCard_03" { source = "CloudCard_03.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = false, stripAnimation = false }
resource "Mesh" "CloudCard_04" { source = "CloudCard_04.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = false, stripAnimation = false }
resource "Mesh" "Cube" { source = "Cube.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "DCube" { source = "DCube.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "DCube2" { source = "DCube2.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "DarkStoneCrystal_01" { source = "DarkStoneCrystal_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "MapShrineSymbol_01" { source = "MapShrineSymbol_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = false, stripAnimation = false }
resource "Mesh" "MapShrine_03" { source = "MapShrine_03.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "MapShrine_04" { source = "MapShrine_04.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "NightBirdFlap01" { source = "NightBirdFlap01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "NightBirdPerchPose_01" { source = "NightBirdPerchPose_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "NightBirdPerchPose_02" { source = "NightBirdPerchPose_02.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "NightBirdTakeOff" { source = "NightBirdTakeOff.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "OrbitMidWaterfall_01" { source = "OrbitMidWaterfall_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = false, stripAnimation = false }
resource "Mesh" "PrairieCrystalCaveDecal_01" { source = "PrairieCrystalCaveDecal_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "PrairieCrystalCaveDecal_02" { source = "PrairieCrystalCaveDecal_02.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "PrairieCrystalCaveMural_01" { source = "PrairieCrystalCaveMural_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "PrairieCrystalCaveMural_02" { source = "PrairieCrystalCaveMural_02.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "PrairieCrystalCaveMural_03" { source = "PrairieCrystalCaveMural_03.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "PrairieCrystalCaveMural_04" { source = "PrairieCrystalCaveMural_04.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "PrairieIslandWater_01" { source = "PrairieIslandWater_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = false, stripAnimation = false }
resource "Mesh" "PropAP10Fireplace_01" { source = "PropAP10Fireplace_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "Prop_AP19CrystalJar_EMPTY" { source = "Prop_AP19CrystalJar_EMPTY.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "RockSimple_01" { source = "RockSimple_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "RockSimple_05" { source = "RockSimple_05.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "RockSimple_09" { source = "RockSimple_09.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "WaterfallRipple_01" { source = "WaterfallRipple_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = false, stripAnimation = false }
resource "Mesh" "Waterfall_01" { source = "Waterfall_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }

-- Animations
resource "AnimationPack" "CharKidAnimEmote_D" {}
resource "AnimationPack" "CharKidAnimEmote_G" {}
resource "AnimationPack" "CharKidAnimGroundState" {}
resource "AnimationPack" "CharKidAnimPlayerAct" {}
resource "AnimationPack" "CharSpiritCinematicAnim_C" {}
resource "AnimationPack" "CharSpiritCinematicAnim_D" {}
resource "AnimationPack" "CharSpiritMemoryPoses" {}
resource "AnimationPack" "ColFatLaborGlobal" {}
resource "AnimationPack" "GenericMemoryPoses" {}
resource "AnimationPack" "MemDayWave" {}
resource "AnimationPack" "SpiritFatLaborEmotes" {}

-- Images
resourceref "Image" "AncestorBlue"
resourceref "Image" "AvatarMaskBasicTex"
resourceref "Image" "CharRampS19"
resourceref "Image" "CharSkyRayBasicTex"
resourceref "Image" "CharSkyRayBasicTexSh"
resourceref "Image" "Clear"
resourceref "Image" "CloudFarTex"
resourceref "Image" "CloudFinTex"
resourceref "Image" "CreatureRamp"
resourceref "Image" "CyanL2"
resourceref "Image" "CyanL3"
resourceref "Image" "DayIntroGate"
resourceref "Image" "DayIntroGateSh"
resourceref "Image" "GrayL1"
resourceref "Image" "Noise3Ch"
resourceref "Image" "StoneBase"
resourceref "Image" "StoneBaseMotif"
resourceref "Image" "StoneBaseMotifSh"
resourceref "Image" "StoneBaseSh"
resourceref "Image" "StoneGrunge2"
resourceref "Image" "StoneRamp"
resourceref "Image" "StoryGeneral"
resourceref "Image" "TileFloor"
resourceref "Image" "TileFloorSh"
resourceref "Image" "UpNormal"
resourceref "Image" "WallBrick"
resourceref "Image" "WallBrickSh"
resourceref "Image" "WaterfallScrolling"
resourceref "Image" "White"

-- Required resources from level object metadata

-- Bake data
resource "LevelData" "Prairie_WildLifePark" { source = "Levels/Prairie_WildLifePark/BstBaked.meshes", lodToLoad = 0 }
