-- THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY THIS FILE!

-- Level objects
resource "LevelObjects" "DuskEnd" { level = "DuskEnd", source = "Levels/DuskEnd/Objects.level", sourcesCount = 12, sources = { "Levels/DuskEnd/Objects.level", "Levels/DuskEnd/Candles.level", "Levels/DuskEnd/Cinematics.level", "Levels/DuskEnd/ConstructionHint.level", "Levels/DuskEnd/Map.level", "Levels/DuskEnd/Marketing_VideoFootage.level", "Levels/DuskEnd/Shop.level", "Levels/DuskEnd/Survey.level", "Levels/DuskEnd/Table.level", "Levels/DuskEnd/TempleExitEvents.level", "Levels/DuskEnd/TempleInteriorArt.level", "Levels/DuskEnd/WingBuff.level" }, stripDebug = true }

-- Prefabs
resource "LevelObjects" "BlobPrefab_SandDeepDune_10" { level = "SandDeepDune_10", source = "BlobPrefabs/SandDeepDune_10/Objects.level", sourcesCount = 1, sources = { "BlobPrefabs/SandDeepDune_10/Objects.level" }, stripDebug = true }
resource "LevelObjects" "BlobPrefab_SandDeepDune_20" { level = "SandDeepDune_20", source = "BlobPrefabs/SandDeepDune_20/Objects.level", sourcesCount = 1, sources = { "BlobPrefabs/SandDeepDune_20/Objects.level" }, stripDebug = true }
resource "LevelObjects" "BlobPrefab_SandDeepDune_30" { level = "SandDeepDune_30", source = "BlobPrefabs/SandDeepDune_30/Objects.level", sourcesCount = 1, sources = { "BlobPrefabs/SandDeepDune_30/Objects.level" }, stripDebug = true }

-- Haptics
resource "HapticFile" "BigBump" { source = "BigBump" }

resource "HapticFile" "JailDoorOpen" { source = "JailDoorOpen" }

resource "HapticFile" "JailDoorStop" { source = "JailDoorStop" }


-- Meshes
resource "Mesh" "AncestorStatueDusk_01" { source = "AncestorStatueDusk_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "AncestorStatuePlatform_01" { source = "AncestorStatuePlatform_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "CaveEntranceStairs_02" { source = "CaveEntranceStairs_02.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "CaveTemplePillar_02" { source = "CaveTemplePillar_02.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "CharSpiritFatLaborAnimEmotes" { source = "CharSpiritFatLaborAnimEmotes.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "CineAncestorDuskElder" { source = "CineAncestorDuskElder.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "CineAncestorDuskProps" { source = "CineAncestorDuskProps.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "ConstellationDusk_01" { source = "ConstellationDusk_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = false, stripAnimation = false }
resource "Mesh" "ConstellationNodeDiamond" { source = "ConstellationNodeDiamond.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "ConstellationNodeLevel1" { source = "ConstellationNodeLevel1.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "ConstellationNodeLevel1Cham" { source = "ConstellationNodeLevel1Cham.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "ConstellationNodeLevel1StarFlare" { source = "ConstellationNodeLevel1StarFlare.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "Cube" { source = "Cube.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "DawnStupaDoorL_01" { source = "DawnStupaDoorL_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "DawnStupaDoorR_01" { source = "DawnStupaDoorR_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "DaysEndStairs_01" { source = "DaysEndStairs_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "DaysEndStairsTile_01" { source = "DaysEndStairsTile_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "DCube" { source = "DCube.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "DCube2" { source = "DCube2.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "DuskFinalTempleCheap_01" { source = "DuskFinalTempleCheap_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "DuskFinalTempleEntranceGate_01" { source = "DuskFinalTempleEntranceGate_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "Engine_CoreTopBaseB" { source = "Engine_CoreTopBaseB.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "GodLightTemple" { source = "GodLightTemple.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = false, stripAnimation = false }
resource "Mesh" "MoteKeyDiamond05" { source = "MoteKeyDiamond05.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "NightCandleHolder_01" { source = "NightCandleHolder_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "NightShelfDecal_01" { source = "NightShelfDecal_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "RainEntrance_01" { source = "RainEntrance_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "RainEntranceDoorL_01" { source = "RainEntranceDoorL_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "RainEntranceDoorR_01" { source = "RainEntranceDoorR_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "RainGrateL_02" { source = "RainGrateL_02.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "RainGrateR_02" { source = "RainGrateR_02.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "SlidingDoorPuzzleMotifL_01" { source = "SlidingDoorPuzzleMotifL_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "SlidingDoorPuzzleMotifR_01" { source = "SlidingDoorPuzzleMotifR_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "StonePad_01" { source = "StonePad_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "StupaMediumStairs_01" { source = "StupaMediumStairs_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "WeaponShield_01" { source = "WeaponShield_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }
resource "Mesh" "WeaponSpear_01" { source = "WeaponSpear_01.fbx", computeOcclusions = false, computeEdges = false, computeAdjacency = false, compressPositions = false, compressUvs = false, stripUv13 = false, stripNormals = false, forceIndex32 = false, registerCollision = true, stripAnimation = false }

-- Animations
resource "AnimationPack" "ColFatLaborGlobal" {}

-- Images
resourceref "Image" "AncestorBlueL1" 
resourceref "Image" "AncestorShrineSh" 
resourceref "Image" "AvatarMaskBasicChamTex" 
resourceref "Image" "AvatarMaskBasicTex" 
resourceref "Image" "BasicGeoAtlas1" 
resourceref "Image" "BlueL1" 
resourceref "Image" "Clear" 
resourceref "Image" "DawnIntroGate" 
resourceref "Image" "DawnIntroGateSh" 
resourceref "Image" "FeatherNoise" 
resourceref "Image" "Gray" 
resourceref "Image" "GreenL2" 
resourceref "Image" "Noise3Ch" 
resourceref "Image" "OrangeL1" 
resourceref "Image" "OrangeL2" 
resourceref "Image" "StoneBase" 
resourceref "Image" "StoneBaseSh" 
resourceref "Image" "StoneGrunge" 
resourceref "Image" "StoneGrunge2" 
resourceref "Image" "StoneRamp" 
resourceref "Image" "StupaBell" 
resourceref "Image" "StupaBellSh" 
resourceref "Image" "UpNormal" 
resourceref "Image" "WallBrick" 
resourceref "Image" "WallBrickSh" 
resourceref "Image" "White" 

-- Required resources from level object metadata

-- Bake data
resource "LevelData" "DuskEnd" { source = "Levels/DuskEnd/BstBaked.meshes", lodToLoad = 0 }
