-- Autogenerated by Tools/Mac/uiatlas.  Do not edit manually.

resourceref "Image" "UiMapAtlas1"

resource "ImageRegion" "UiMapPrairie_Village_Shrine" { image = "UiMapAtlas1", uv = { 0, 0, 0.688965, 0.215332 } }
resource "ImageRegion" "UiMapRainEnd" { image = "UiMapAtlas1", uv = { 0, 0.217285, 0.492676, 0.419922 } }
resource "ImageRegion" "UiMapDuskEnd" { image = "UiMapAtlas1", uv = { 0.494629, 0.217285, 0.947754, 0.522949 } }
resource "ImageRegion" "UiMapDawn_Shrine" { image = "UiMapAtlas1", uv = { 0.494629, 0.524902, 0.89209, 0.903809 } }
resource "ImageRegion" "UiMapCandleSpaceEnd" { image = "UiMapAtlas1", uv = { 0, 0.421875, 0.458496, 0.698242 } }
resource "ImageRegion" "UiMapSunsetColosseum" { image = "UiMapAtlas1", uv = { 0, 0.700195, 0.444824, 0.977051 } }
resourceref "Image" "UiMapAtlas2"

resource "ImageRegion" "UiMapAviaryVillage" { image = "UiMapAtlas2", uv = { 0, 0, 0.370605, 0.265625 } }
resource "ImageRegion" "UiMapDusk_Triangle" { image = "UiMapAtlas2", uv = { 0.372559, 0, 0.714355, 0.21875 } }
resource "ImageRegion" "UiMapPrairie_Island" { image = "UiMapAtlas2", uv = { 0.372559, 0.220703, 0.709961, 0.519531 } }
resource "ImageRegion" "UiMapStormStart" { image = "UiMapAtlas2", uv = { 0.372559, 0.521484, 0.709961, 0.792969 } }
resource "ImageRegion" "UiMapDawn" { image = "UiMapAtlas2", uv = { 0.372559, 0.794922, 0.705566, 0.965332 } }
resource "ImageRegion" "UiMapStorm" { image = "UiMapAtlas2", uv = { 0, 0.267578, 0.366211, 0.748047 } }
resource "ImageRegion" "UiMapDuskOasis" { image = "UiMapAtlas2", uv = { 0, 0.75, 0.34375, 0.902832 } }
resourceref "Image" "UiMapAtlas3"

resource "ImageRegion" "UiMapRain" { image = "UiMapAtlas3", uv = { 0, 0, 0.32666, 0.205566 } }
resource "ImageRegion" "UiMapStormEnd" { image = "UiMapAtlas3", uv = { 0.328613, 0, 0.634277, 0.369629 } }
resource "ImageRegion" "UiMapPrairie_Village" { image = "UiMapAtlas3", uv = { 0.63623, 0, 0.926758, 0.233887 } }
resource "ImageRegion" "UiMapSunset" { image = "UiMapAtlas3", uv = { 0.63623, 0.23584, 0.92627, 0.420898 } }
resource "ImageRegion" "UiMapNight_Shelter" { image = "UiMapAtlas3", uv = { 0.63623, 0.422852, 0.92041, 0.672852 } }
resource "ImageRegion" "UiMapDayHubCave" { image = "UiMapAtlas3", uv = { 0.63623, 0.674805, 0.915039, 0.803711 } }
resource "ImageRegion" "UiMapRainForest" { image = "UiMapAtlas3", uv = { 0.63623, 0.805664, 0.909668, 0.928223 } }
resource "ImageRegion" "UiMapRain_BaseCamp" { image = "UiMapAtlas3", uv = { 0.328613, 0.371582, 0.630371, 0.549805 } }
resource "ImageRegion" "UiMapCandleSpace" { image = "UiMapAtlas3", uv = { 0.328613, 0.551758, 0.62207, 0.812012 } }
resource "ImageRegion" "UiMapPrairie_ButterflyFields" { image = "UiMapAtlas3", uv = { 0.328613, 0.813965, 0.620117, 0.968262 } }
resource "ImageRegion" "UiMapSunsetVillage" { image = "UiMapAtlas3", uv = { 0, 0.20752, 0.326172, 0.434082 } }
resource "ImageRegion" "UiMapRainMid" { image = "UiMapAtlas3", uv = { 0, 0.436035, 0.319824, 0.671387 } }
resource "ImageRegion" "UiMapNight2_SecondFloor" { image = "UiMapAtlas3", uv = { 0, 0.67334, 0.308105, 0.95166 } }
resourceref "Image" "UiMapAtlas4"

resource "ImageRegion" "UiMapSunsetRace" { image = "UiMapAtlas4", uv = { 0, 0, 0.270996, 0.134277 } }
resource "ImageRegion" "UiMapSunset_Citadel" { image = "UiMapAtlas4", uv = { 0.272949, 0, 0.535156, 0.207031 } }
resource "ImageRegion" "UiMapSkyway" { image = "UiMapAtlas4", uv = { 0.272949, 0.208984, 0.533691, 0.448242 } }
resource "ImageRegion" "UiMapDuskStart" { image = "UiMapAtlas4", uv = { 0.272949, 0.450195, 0.524414, 0.664551 } }
resource "ImageRegion" "UiMapDusk_CrabField" { image = "UiMapAtlas4", uv = { 0.526367, 0.450195, 0.774902, 0.663086 } }
resource "ImageRegion" "UiMapSunset_YetiPark" { image = "UiMapAtlas4", uv = { 0.526367, 0.665039, 0.774902, 0.804688 } }
resource "ImageRegion" "UiMapSunset_Theater" { image = "UiMapAtlas4", uv = { 0.272949, 0.666504, 0.523438, 0.887207 } }
resource "ImageRegion" "UiMapDusk" { image = "UiMapAtlas4", uv = { 0.535645, 0.208984, 0.787598, 0.392578 } }
resource "ImageRegion" "UiMapRain_Town" { image = "UiMapAtlas4", uv = { 0.537109, 0, 0.79834, 0.190918 } }
resource "ImageRegion" "UiMapPrairie_NestAndKeeper" { image = "UiMapAtlas4", uv = { 0, 0.13623, 0.27002, 0.334473 } }
resource "ImageRegion" "UiMapSunset_Town" { image = "UiMapAtlas4", uv = { 0, 0.336426, 0.269043, 0.526367 } }
resource "ImageRegion" "UiMapNightDesert" { image = "UiMapAtlas4", uv = { 0, 0.52832, 0.263672, 0.760254 } }
resource "ImageRegion" "UiMapRainShelter" { image = "UiMapAtlas4", uv = { 0, 0.762207, 0.262207, 0.929688 } }
resourceref "Image" "UiMapAtlas5"

resource "ImageRegion" "UiMapPrairie_WildLifePark" { image = "UiMapAtlas5", uv = { 0, 0, 0.245117, 0.217285 } }
resource "ImageRegion" "UiMapNightArchive" { image = "UiMapAtlas5", uv = { 0.24707, 0, 0.481445, 0.16748 } }
resource "ImageRegion" "UiMapStormLight" { image = "UiMapAtlas5", uv = { 0.483398, 0, 0.699707, 0.306641 } }
resource "ImageRegion" "UiMapNight_ThirdFloor" { image = "UiMapAtlas5", uv = { 0.70166, 0, 0.90918, 0.172852 } }
resource "ImageRegion" "UiMapDawn_Start" { image = "UiMapAtlas5", uv = { 0.70166, 0.174805, 0.894043, 0.269043 } }
resource "ImageRegion" "UiMapDawn_Plateau" { image = "UiMapAtlas5", uv = { 0.70166, 0.270996, 0.878418, 0.427734 } }
resource "ImageRegion" "UiMapSunsetVillage_MusicShop" { image = "UiMapAtlas5", uv = { 0.70166, 0.429688, 0.867188, 0.543457 } }
resource "ImageRegion" "UiMapDawn_TrialsFire" { image = "UiMapAtlas5", uv = { 0.70166, 0.54541, 0.866211, 0.706543 } }
resource "ImageRegion" "UiMapDawn_TrialsEarth" { image = "UiMapAtlas5", uv = { 0.70166, 0.708496, 0.856934, 0.862305 } }
resource "ImageRegion" "UiMapIPC_ColoredDeer" { image = "UiMapAtlas5", uv = { 0.483398, 0.308594, 0.695312, 0.495117 } }
resource "ImageRegion" "UiMapIPC_AuroraConcert" { image = "UiMapAtlas5", uv = { 0.483398, 0.49707, 0.693848, 0.682129 } }
resource "ImageRegion" "UiMapNight2" { image = "UiMapAtlas5", uv = { 0.483398, 0.684082, 0.691895, 0.833496 } }
resource "ImageRegion" "UiMapRainEnd_Pond" { image = "UiMapAtlas5", uv = { 0.483398, 0.835449, 0.677246, 0.974609 } }
resource "ImageRegion" "UiMapNight_IPHallway" { image = "UiMapAtlas5", uv = { 0.24707, 0.169434, 0.479004, 0.373535 } }
resource "ImageRegion" "UiMapPrairie_ButterflyFields_Town" { image = "UiMapAtlas5", uv = { 0.24707, 0.375488, 0.477539, 0.522461 } }
resource "ImageRegion" "UiMapNight" { image = "UiMapAtlas5", uv = { 0.24707, 0.524414, 0.475586, 0.681152 } }
resource "ImageRegion" "UiMapPrairie_Cave" { image = "UiMapAtlas5", uv = { 0.24707, 0.683105, 0.46875, 0.841797 } }
resource "ImageRegion" "UiMapSunset_FlyRace" { image = "UiMapAtlas5", uv = { 0.24707, 0.84375, 0.460938, 0.959961 } }
resource "ImageRegion" "UiMapDawnCave" { image = "UiMapAtlas5", uv = { 0, 0.219238, 0.236816, 0.405762 } }
resource "ImageRegion" "UiMapDuskGraveyard" { image = "UiMapAtlas5", uv = { 0, 0.407715, 0.235352, 0.553223 } }
resource "ImageRegion" "UiMapRain_Cave" { image = "UiMapAtlas5", uv = { 0, 0.555176, 0.235352, 0.717773 } }
resource "ImageRegion" "UiMapDuskMid" { image = "UiMapAtlas5", uv = { 0, 0.719727, 0.234863, 0.97168 } }
resourceref "Image" "UiMapAtlas6"

resource "ImageRegion" "UiMapDawn_TrialsAir" { image = "UiMapAtlas6", uv = { 0, 0, 0.151367, 0.146973 } }
resource "ImageRegion" "UiMapTGCOffice" { image = "UiMapAtlas6", uv = { 0, 0.148926, 0.151367, 0.29834 } }
resource "ImageRegion" "UiMapPlayerShadow" { image = "UiMapAtlas6", uv = { 0.15332, 0.148926, 0.222656, 0.218262 } }
resource "ImageRegion" "UiMapSpirit" { image = "UiMapAtlas6", uv = { 0.224609, 0.148926, 0.28418, 0.208496 } }
resource "ImageRegion" "UiMapDawn_TrialsWater" { image = "UiMapAtlas6", uv = { 0.15332, 0, 0.294434, 0.141113 } }
resource "ImageRegion" "UiMapBeaconLinesGlow" { image = "UiMapAtlas6", uv = { 0.296387, 0, 0.38916, 0.092773 } }
resource "ImageRegion" "UiMapBeaconDotGlow" { image = "UiMapAtlas6", uv = { 0.391113, 0, 0.480957, 0.089844 } }
resource "ImageRegion" "UiMapStar" { image = "UiMapAtlas6", uv = { 0.391113, 0.091797, 0.443848, 0.144531 } }
resource "ImageRegion" "UiMapBeaconOutlineGlow" { image = "UiMapAtlas6", uv = { 0.48291, 0, 0.571777, 0.088867 } }
resource "ImageRegion" "UiMapBeaconOutline" { image = "UiMapAtlas6", uv = { 0.57373, 0, 0.650879, 0.077148 } }
resource "ImageRegion" "UiMapBeaconBg" { image = "UiMapAtlas6", uv = { 0.652832, 0, 0.728027, 0.075195 } }
resource "ImageRegion" "UiMapBeaconDot" { image = "UiMapAtlas6", uv = { 0.72998, 0, 0.805176, 0.075195 } }
resource "ImageRegion" "UiMapBeaconLines" { image = "UiMapAtlas6", uv = { 0.807129, 0, 0.882324, 0.075195 } }
resource "ImageRegion" "UiMapPlayer" { image = "UiMapAtlas6", uv = { 0.884277, 0, 0.953613, 0.069336 } }
resource "ImageRegion" "UiMapPath" { image = "UiMapAtlas6", uv = { 0.955566, 0, 0.975098, 0.019531 } }
