-- Autogenerated by Tools/Mac/uiatlas.  Do not edit manually.

resourceref "Image" "UiMapAtlas1"

resource "ImageRegion" "UiMapPrairie_Village_Shrine" { image = "UiMapAtlas1", uv = { 0, 0, 0.688965, 0.215332 } }
resource "ImageRegion" "UiMapRainEnd" { image = "UiMapAtlas1", uv = { 0, 0.217285, 0.492676, 0.419922 } }
resource "ImageRegion" "UiMapDuskEnd" { image = "UiMapAtlas1", uv = { 0.494629, 0.217285, 0.947754, 0.522949 } }
resource "ImageRegion" "UiMapDawn_Shrine" { image = "UiMapAtlas1", uv = { 0.494629, 0.524902, 0.89209, 0.903809 } }
resource "ImageRegion" "UiMapCandleSpaceEnd" { image = "UiMapAtlas1", uv = { 0, 0.421875, 0.458496, 0.698242 } }
resource "ImageRegion" "UiMapSunsetColosseum" { image = "UiMapAtlas1", uv = { 0, 0.700195, 0.444824, 0.977051 } }
resourceref "Image" "UiMapAtlas2"

resource "ImageRegion" "UiMapAviaryVillage" { image = "UiMapAtlas2", uv = { 0, 0, 0.370605, 0.265625 } }
resource "ImageRegion" "UiMapDusk_Triangle" { image = "UiMapAtlas2", uv = { 0.372559, 0, 0.714355, 0.21875 } }
resource "ImageRegion" "UiMapPrairie_Island" { image = "UiMapAtlas2", uv = { 0.372559, 0.220703, 0.709961, 0.519531 } }
resource "ImageRegion" "UiMapStormStart" { image = "UiMapAtlas2", uv = { 0.372559, 0.521484, 0.709961, 0.792969 } }
resource "ImageRegion" "UiMapDawn" { image = "UiMapAtlas2", uv = { 0.372559, 0.794922, 0.705566, 0.965332 } }
resource "ImageRegion" "UiMapStorm" { image = "UiMapAtlas2", uv = { 0, 0.267578, 0.366211, 0.748047 } }
resource "ImageRegion" "UiMapDuskOasis" { image = "UiMapAtlas2", uv = { 0, 0.75, 0.34375, 0.902832 } }
resourceref "Image" "UiMapAtlas3"

resource "ImageRegion" "UiMapRain" { image = "UiMapAtlas3", uv = { 0, 0, 0.32666, 0.205566 } }
resource "ImageRegion" "UiMapStormEnd" { image = "UiMapAtlas3", uv = { 0.328613, 0, 0.634277, 0.369629 } }
resource "ImageRegion" "UiMapCandleSpace" { image = "UiMapAtlas3", uv = { 0.63623, 0, 0.929688, 0.260254 } }
resource "ImageRegion" "UiMapPrairie_Village" { image = "UiMapAtlas3", uv = { 0.63623, 0.262207, 0.926758, 0.496094 } }
resource "ImageRegion" "UiMapSunset" { image = "UiMapAtlas3", uv = { 0.63623, 0.498047, 0.92627, 0.683105 } }
resource "ImageRegion" "UiMapNight_Shelter" { image = "UiMapAtlas3", uv = { 0.63623, 0.685059, 0.92041, 0.935059 } }
resource "ImageRegion" "UiMapRain_BaseCamp" { image = "UiMapAtlas3", uv = { 0.328613, 0.371582, 0.630371, 0.549805 } }
resource "ImageRegion" "UiMapNight_PaintedWorld" { image = "UiMapAtlas3", uv = { 0.328613, 0.551758, 0.625, 0.8125 } }
resource "ImageRegion" "UiMapPrairie_ButterflyFields" { image = "UiMapAtlas3", uv = { 0.328613, 0.814453, 0.620117, 0.96875 } }
resource "ImageRegion" "UiMapSunsetVillage" { image = "UiMapAtlas3", uv = { 0, 0.20752, 0.326172, 0.434082 } }
resource "ImageRegion" "UiMapRainMid" { image = "UiMapAtlas3", uv = { 0, 0.436035, 0.319824, 0.671387 } }
resource "ImageRegion" "UiMapNight2_SecondFloor" { image = "UiMapAtlas3", uv = { 0, 0.67334, 0.308105, 0.95166 } }
resourceref "Image" "UiMapAtlas4"

resource "ImageRegion" "UiMapDayHubCave" { image = "UiMapAtlas4", uv = { 0, 0, 0.278809, 0.128906 } }
resource "ImageRegion" "UiMapSunsetRace" { image = "UiMapAtlas4", uv = { 0, 0.130859, 0.270996, 0.265137 } }
resource "ImageRegion" "UiMapPrairie_NestAndKeeper" { image = "UiMapAtlas4", uv = { 0, 0.26709, 0.27002, 0.465332 } }
resource "ImageRegion" "UiMapRainShelter" { image = "UiMapAtlas4", uv = { 0.271973, 0.26709, 0.53418, 0.43457 } }
resource "ImageRegion" "UiMapSunset_Citadel" { image = "UiMapAtlas4", uv = { 0.271973, 0.436523, 0.53418, 0.643555 } }
resource "ImageRegion" "UiMapSkyway" { image = "UiMapAtlas4", uv = { 0.271973, 0.645508, 0.532715, 0.884766 } }
resource "ImageRegion" "UiMapDusk" { image = "UiMapAtlas4", uv = { 0.534668, 0.645508, 0.786621, 0.829102 } }
resource "ImageRegion" "UiMapRain_Town" { image = "UiMapAtlas4", uv = { 0.536133, 0.436523, 0.797363, 0.627441 } }
resource "ImageRegion" "UiMapSunset_Town" { image = "UiMapAtlas4", uv = { 0, 0.467285, 0.269043, 0.657227 } }
resource "ImageRegion" "UiMapNightDesert" { image = "UiMapAtlas4", uv = { 0, 0.65918, 0.263672, 0.891113 } }
resource "ImageRegion" "UiMapRainForest" { image = "UiMapAtlas4", uv = { 0.280762, 0, 0.554199, 0.122559 } }
resourceref "Image" "UiMapAtlas5"

resource "ImageRegion" "UiMapDuskStart" { image = "UiMapAtlas5", uv = { 0, 0, 0.251465, 0.214355 } }
resource "ImageRegion" "UiMapSunset_Theater" { image = "UiMapAtlas5", uv = { 0, 0.216309, 0.250488, 0.437012 } }
resource "ImageRegion" "UiMapPrairie_WildLifePark" { image = "UiMapAtlas5", uv = { 0.252441, 0.216309, 0.497559, 0.433594 } }
resource "ImageRegion" "UiMapDuskMid" { image = "UiMapAtlas5", uv = { 0.252441, 0.435547, 0.487305, 0.6875 } }
resource "ImageRegion" "UiMapStormLight" { image = "UiMapAtlas5", uv = { 0.252441, 0.689453, 0.46875, 0.996094 } }
resource "ImageRegion" "UiMapSunset_FlyRace" { image = "UiMapAtlas5", uv = { 0.470703, 0.689453, 0.68457, 0.805664 } }
resource "ImageRegion" "UiMapIPC_AuroraConcert" { image = "UiMapAtlas5", uv = { 0.470703, 0.807617, 0.681152, 0.992676 } }
resource "ImageRegion" "UiMapNight2" { image = "UiMapAtlas5", uv = { 0.683105, 0.807617, 0.891602, 0.957031 } }
resource "ImageRegion" "UiMapNightArchive" { image = "UiMapAtlas5", uv = { 0.489258, 0.435547, 0.723633, 0.603027 } }
resource "ImageRegion" "UiMapNight_IPHallway" { image = "UiMapAtlas5", uv = { 0.725586, 0.435547, 0.95752, 0.639648 } }
resource "ImageRegion" "UiMapDuskGraveyard" { image = "UiMapAtlas5", uv = { 0.499512, 0.216309, 0.734863, 0.361816 } }
resource "ImageRegion" "UiMapRain_Cave" { image = "UiMapAtlas5", uv = { 0.736816, 0.216309, 0.972168, 0.378906 } }
resource "ImageRegion" "UiMapDusk_CrabField" { image = "UiMapAtlas5", uv = { 0, 0.438965, 0.248535, 0.651855 } }
resource "ImageRegion" "UiMapSunset_YetiPark" { image = "UiMapAtlas5", uv = { 0, 0.653809, 0.248535, 0.793457 } }
resource "ImageRegion" "UiMapDawnCave" { image = "UiMapAtlas5", uv = { 0, 0.79541, 0.236816, 0.981934 } }
resource "ImageRegion" "UiMapPrairie_ButterflyFields_Town" { image = "UiMapAtlas5", uv = { 0.253418, 0, 0.483887, 0.146973 } }
resource "ImageRegion" "UiMapNight" { image = "UiMapAtlas5", uv = { 0.48584, 0, 0.714355, 0.156738 } }
resource "ImageRegion" "UiMapPrairie_Cave" { image = "UiMapAtlas5", uv = { 0.716309, 0, 0.937988, 0.158691 } }
resourceref "Image" "UiMapAtlas6"

resource "ImageRegion" "UiMapNight_ThirdFloor" { image = "UiMapAtlas6", uv = { 0, 0, 0.20752, 0.172852 } }
resource "ImageRegion" "UiMapDawn_TrialsEarth" { image = "UiMapAtlas6", uv = { 0.209473, 0, 0.364746, 0.153809 } }
resource "ImageRegion" "UiMapBeaconOutline" { image = "UiMapAtlas6", uv = { 0.209473, 0.155762, 0.286621, 0.23291 } }
resource "ImageRegion" "UiMapBeaconBg" { image = "UiMapAtlas6", uv = { 0.288574, 0.155762, 0.36377, 0.230957 } }
resource "ImageRegion" "UiMapBeaconDot" { image = "UiMapAtlas6", uv = { 0.365723, 0.155762, 0.440918, 0.230957 } }
resource "ImageRegion" "UiMapBeaconLines" { image = "UiMapAtlas6", uv = { 0.442871, 0.155762, 0.518066, 0.230957 } }
resource "ImageRegion" "UiMapPlayer" { image = "UiMapAtlas6", uv = { 0.52002, 0.155762, 0.589355, 0.225098 } }
resource "ImageRegion" "UiMapPlayerShadow" { image = "UiMapAtlas6", uv = { 0.591309, 0.155762, 0.660645, 0.225098 } }
resource "ImageRegion" "UiMapSpirit" { image = "UiMapAtlas6", uv = { 0.662598, 0.155762, 0.722168, 0.215332 } }
resource "ImageRegion" "UiMapTGCOffice" { image = "UiMapAtlas6", uv = { 0.366699, 0, 0.518066, 0.149414 } }
resource "ImageRegion" "UiMapDawn_TrialsWater" { image = "UiMapAtlas6", uv = { 0.52002, 0, 0.661133, 0.141113 } }
resource "ImageRegion" "UiMapBeaconLinesGlow" { image = "UiMapAtlas6", uv = { 0.663086, 0, 0.755859, 0.092773 } }
resource "ImageRegion" "UiMapBeaconDotGlow" { image = "UiMapAtlas6", uv = { 0.757812, 0, 0.847656, 0.089844 } }
resource "ImageRegion" "UiMapBeaconOutlineGlow" { image = "UiMapAtlas6", uv = { 0.849609, 0, 0.938477, 0.088867 } }
resource "ImageRegion" "UiMapPath" { image = "UiMapAtlas6", uv = { 0.663086, 0.094727, 0.682617, 0.114258 } }
resource "ImageRegion" "UiMapRainEnd_Pond" { image = "UiMapAtlas6", uv = { 0, 0.174805, 0.193848, 0.313965 } }
resource "ImageRegion" "UiMapDawn_Start" { image = "UiMapAtlas6", uv = { 0, 0.315918, 0.192383, 0.410156 } }
resource "ImageRegion" "UiMapDawn_Plateau" { image = "UiMapAtlas6", uv = { 0, 0.412109, 0.176758, 0.568848 } }
resource "ImageRegion" "UiMapSunsetVillage_MusicShop" { image = "UiMapAtlas6", uv = { 0, 0.570801, 0.165527, 0.68457 } }
resource "ImageRegion" "UiMapDawn_TrialsFire" { image = "UiMapAtlas6", uv = { 0, 0.686523, 0.164551, 0.847656 } }
resource "ImageRegion" "UiMapDawn_TrialsAir" { image = "UiMapAtlas6", uv = { 0, 0.849609, 0.151367, 0.996582 } }
resource "ImageRegion" "UiMapStar" { image = "UiMapAtlas6", uv = { 0.15332, 0.849609, 0.206055, 0.902344 } }
