-- Autogenerated by Tools/Mac/uiatlas.  Do not edit manually.

resourceref "Image" "UiMapAtlas1"

resource "ImageRegion" "UiMapPrairie_Village_Shrine" { image = "UiMapAtlas1", uv = { 0, 0, 0.688965, 0.215332 } }
resource "ImageRegion" "UiMapRainEnd" { image = "UiMapAtlas1", uv = { 0, 0.217285, 0.492676, 0.419922 } }
resource "ImageRegion" "UiMapDuskEnd" { image = "UiMapAtlas1", uv = { 0.494629, 0.217285, 0.947754, 0.522949 } }
resource "ImageRegion" "UiMapDawn_Shrine" { image = "UiMapAtlas1", uv = { 0.494629, 0.524902, 0.89209, 0.903809 } }
resource "ImageRegion" "UiMapCandleSpaceEnd" { image = "UiMapAtlas1", uv = { 0, 0.421875, 0.458496, 0.698242 } }
resource "ImageRegion" "UiMapSunsetColosseum" { image = "UiMapAtlas1", uv = { 0, 0.700195, 0.444824, 0.977051 } }
resourceref "Image" "UiMapAtlas2"

resource "ImageRegion" "UiMapAviaryVillage" { image = "UiMapAtlas2", uv = { 0, 0, 0.370605, 0.265625 } }
resource "ImageRegion" "UiMapDusk_Triangle" { image = "UiMapAtlas2", uv = { 0.372559, 0, 0.714355, 0.21875 } }
resource "ImageRegion" "UiMapPrairie_Island" { image = "UiMapAtlas2", uv = { 0.372559, 0.220703, 0.709961, 0.519531 } }
resource "ImageRegion" "UiMapStormStart" { image = "UiMapAtlas2", uv = { 0.372559, 0.521484, 0.709961, 0.792969 } }
resource "ImageRegion" "UiMapDawn" { image = "UiMapAtlas2", uv = { 0.372559, 0.794922, 0.705566, 0.965332 } }
resource "ImageRegion" "UiMapStorm" { image = "UiMapAtlas2", uv = { 0, 0.267578, 0.366211, 0.748047 } }
resource "ImageRegion" "UiMapDuskOasis" { image = "UiMapAtlas2", uv = { 0, 0.75, 0.34375, 0.902832 } }
resourceref "Image" "UiMapAtlas3"

resource "ImageRegion" "UiMapRain" { image = "UiMapAtlas3", uv = { 0, 0, 0.32666, 0.205566 } }
resource "ImageRegion" "UiMapStormEnd" { image = "UiMapAtlas3", uv = { 0.328613, 0, 0.634277, 0.369629 } }
resource "ImageRegion" "UiMapPrairie_Village" { image = "UiMapAtlas3", uv = { 0.63623, 0, 0.926758, 0.233887 } }
resource "ImageRegion" "UiMapSunset" { image = "UiMapAtlas3", uv = { 0.63623, 0.23584, 0.92627, 0.420898 } }
resource "ImageRegion" "UiMapNight_Shelter" { image = "UiMapAtlas3", uv = { 0.63623, 0.422852, 0.92041, 0.672852 } }
resource "ImageRegion" "UiMapDayHubCave" { image = "UiMapAtlas3", uv = { 0.63623, 0.674805, 0.915039, 0.803711 } }
resource "ImageRegion" "UiMapRainForest" { image = "UiMapAtlas3", uv = { 0.63623, 0.805664, 0.909668, 0.928223 } }
resource "ImageRegion" "UiMapRain_BaseCamp" { image = "UiMapAtlas3", uv = { 0.328613, 0.371582, 0.630371, 0.549805 } }
resource "ImageRegion" "UiMapCandleSpace" { image = "UiMapAtlas3", uv = { 0.328613, 0.551758, 0.62207, 0.812012 } }
resource "ImageRegion" "UiMapPrairie_ButterflyFields" { image = "UiMapAtlas3", uv = { 0.328613, 0.813965, 0.620117, 0.968262 } }
resource "ImageRegion" "UiMapSunsetVillage" { image = "UiMapAtlas3", uv = { 0, 0.20752, 0.326172, 0.434082 } }
resource "ImageRegion" "UiMapRainMid" { image = "UiMapAtlas3", uv = { 0, 0.436035, 0.319824, 0.671387 } }
resource "ImageRegion" "UiMapNight2_SecondFloor" { image = "UiMapAtlas3", uv = { 0, 0.67334, 0.308105, 0.95166 } }
resourceref "Image" "UiMapAtlas4"

resource "ImageRegion" "UiMapSunsetRace" { image = "UiMapAtlas4", uv = { 0, 0, 0.270996, 0.134277 } }
resource "ImageRegion" "UiMapRain_Town" { image = "UiMapAtlas4", uv = { 0.272949, 0, 0.53418, 0.190918 } }
resource "ImageRegion" "UiMapSunset_Theater" { image = "UiMapAtlas4", uv = { 0.536133, 0, 0.786621, 0.220703 } }
resource "ImageRegion" "UiMapDusk_CrabField" { image = "UiMapAtlas4", uv = { 0.536133, 0.222656, 0.784668, 0.435547 } }
resource "ImageRegion" "UiMapPrairie_WildLifePark" { image = "UiMapAtlas4", uv = { 0.536133, 0.4375, 0.78125, 0.654785 } }
resource "ImageRegion" "UiMapDawnCave" { image = "UiMapAtlas4", uv = { 0.536133, 0.656738, 0.772949, 0.843262 } }
resource "ImageRegion" "UiMapDuskGraveyard" { image = "UiMapAtlas4", uv = { 0.536133, 0.845215, 0.771484, 0.990723 } }
resource "ImageRegion" "UiMapSkyway" { image = "UiMapAtlas4", uv = { 0.272949, 0.192871, 0.533691, 0.432129 } }
resource "ImageRegion" "UiMapDusk" { image = "UiMapAtlas4", uv = { 0.272949, 0.434082, 0.524902, 0.617676 } }
resource "ImageRegion" "UiMapDuskStart" { image = "UiMapAtlas4", uv = { 0.272949, 0.619629, 0.524414, 0.833984 } }
resource "ImageRegion" "UiMapSunset_YetiPark" { image = "UiMapAtlas4", uv = { 0.272949, 0.835938, 0.521484, 0.975586 } }
resource "ImageRegion" "UiMapPrairie_NestAndKeeper" { image = "UiMapAtlas4", uv = { 0, 0.13623, 0.27002, 0.334473 } }
resource "ImageRegion" "UiMapSunset_Town" { image = "UiMapAtlas4", uv = { 0, 0.336426, 0.269043, 0.526367 } }
resource "ImageRegion" "UiMapRainShelter" { image = "UiMapAtlas4", uv = { 0, 0.52832, 0.262207, 0.695801 } }
resource "ImageRegion" "UiMapSunset_Citadel" { image = "UiMapAtlas4", uv = { 0, 0.697754, 0.262207, 0.904785 } }
resourceref "Image" "UiMapAtlas5"

resource "ImageRegion" "UiMapRain_Cave" { image = "UiMapAtlas5", uv = { 0, 0, 0.235352, 0.162598 } }
resource "ImageRegion" "UiMapDuskMid" { image = "UiMapAtlas5", uv = { 0, 0.164551, 0.234863, 0.416504 } }
resource "ImageRegion" "UiMapPrairie_Cave" { image = "UiMapAtlas5", uv = { 0, 0.418457, 0.22168, 0.577148 } }
resource "ImageRegion" "UiMapStormLight" { image = "UiMapAtlas5", uv = { 0.223633, 0.418457, 0.439941, 0.725098 } }
resource "ImageRegion" "UiMapDawn_TrialsEarth" { image = "UiMapAtlas5", uv = { 0.223633, 0.727051, 0.378906, 0.880859 } }
resource "ImageRegion" "UiMapDawn_TrialsAir" { image = "UiMapAtlas5", uv = { 0.380859, 0.727051, 0.532227, 0.874023 } }
resource "ImageRegion" "UiMapTGCOffice" { image = "UiMapAtlas5", uv = { 0.53418, 0.727051, 0.685547, 0.876465 } }
resource "ImageRegion" "UiMapNight_ThirdFloor" { image = "UiMapAtlas5", uv = { 0.441895, 0.418457, 0.649414, 0.591309 } }
resource "ImageRegion" "UiMapDawn_Plateau" { image = "UiMapAtlas5", uv = { 0.651367, 0.418457, 0.828125, 0.575195 } }
resource "ImageRegion" "UiMapDawn_TrialsFire" { image = "UiMapAtlas5", uv = { 0.830078, 0.418457, 0.994629, 0.57959 } }
resource "ImageRegion" "UiMapDawn_TrialsWater" { image = "UiMapAtlas5", uv = { 0.830078, 0.581543, 0.971191, 0.722656 } }
resource "ImageRegion" "UiMapSunsetVillage_MusicShop" { image = "UiMapAtlas5", uv = { 0.651367, 0.577148, 0.816895, 0.690918 } }
resource "ImageRegion" "UiMapDawn_Start" { image = "UiMapAtlas5", uv = { 0.441895, 0.593262, 0.634277, 0.6875 } }
resource "ImageRegion" "UiMapNightDesert" { image = "UiMapAtlas5", uv = { 0, 0.579102, 0.221191, 0.773438 } }
resource "ImageRegion" "UiMapNight2" { image = "UiMapAtlas5", uv = { 0, 0.775391, 0.208496, 0.924805 } }
resource "ImageRegion" "UiMapPlayerShadow" { image = "UiMapAtlas5", uv = { 0, 0.926758, 0.069336, 0.996094 } }
resource "ImageRegion" "UiMapSpirit" { image = "UiMapAtlas5", uv = { 0.071289, 0.926758, 0.130859, 0.986328 } }
resource "ImageRegion" "UiMapStar" { image = "UiMapAtlas5", uv = { 0.132812, 0.926758, 0.185547, 0.979492 } }
resource "ImageRegion" "UiMapPath" { image = "UiMapAtlas5", uv = { 0.1875, 0.926758, 0.207031, 0.946289 } }
resource "ImageRegion" "UiMapNightArchive" { image = "UiMapAtlas5", uv = { 0.236816, 0.164551, 0.471191, 0.332031 } }
resource "ImageRegion" "UiMapNight" { image = "UiMapAtlas5", uv = { 0.473145, 0.164551, 0.70166, 0.321289 } }
resource "ImageRegion" "UiMapSunset_FlyRace" { image = "UiMapAtlas5", uv = { 0.703613, 0.164551, 0.91748, 0.280762 } }
resource "ImageRegion" "UiMapBeaconOutline" { image = "UiMapAtlas5", uv = { 0.919434, 0.164551, 0.996582, 0.241699 } }
resource "ImageRegion" "UiMapBeaconBg" { image = "UiMapAtlas5", uv = { 0.919434, 0.243652, 0.994629, 0.318848 } }
resource "ImageRegion" "UiMapBeaconDot" { image = "UiMapAtlas5", uv = { 0.236816, 0.333984, 0.312012, 0.40918 } }
resource "ImageRegion" "UiMapBeaconLines" { image = "UiMapAtlas5", uv = { 0.313965, 0.333984, 0.38916, 0.40918 } }
resource "ImageRegion" "UiMapPlayer" { image = "UiMapAtlas5", uv = { 0.391113, 0.333984, 0.460449, 0.40332 } }
resource "ImageRegion" "UiMapPrairie_ButterflyFields_Town" { image = "UiMapAtlas5", uv = { 0.237305, 0, 0.467773, 0.146973 } }
resource "ImageRegion" "UiMapRainEnd_Pond" { image = "UiMapAtlas5", uv = { 0.469727, 0, 0.663574, 0.13916 } }
resource "ImageRegion" "UiMapBeaconLinesGlow" { image = "UiMapAtlas5", uv = { 0.665527, 0, 0.758301, 0.092773 } }
resource "ImageRegion" "UiMapBeaconDotGlow" { image = "UiMapAtlas5", uv = { 0.760254, 0, 0.850098, 0.089844 } }
resource "ImageRegion" "UiMapBeaconOutlineGlow" { image = "UiMapAtlas5", uv = { 0.852051, 0, 0.940918, 0.088867 } }
