-- THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY THIS FILE!
resource "LevelObjects" "WorldEmpty" { level = "WorldEmpty", source = "Levels/WorldEmpty/Objects.level", stripDebug = true }

resource "LevelData" "WorldEmpty" { source = "Levels/WorldEmpty/BstBaked.meshes", lodToLoad = 0 }

-- Meshes

-- Images
